name: Newly
favicon: null
layout_spectrum: 0.9849105509929359
typography_spectrum: 0.4957785939332098
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5404177180025727
  lightness: 0.9638045069295913
  saturation: 0.5016777038108557
  rhythmicContrast: 0.16053681098856032
purpose: []
