name: Newly
favicon: null
layout_spectrum: 0.74653
typography_spectrum: 0.25328
title: Newly Design Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1932'
    - '#ffffff'
    - '#ef91d3'
    - '#f9996f'
    - '#ee2865'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
